force-app/main/default/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Application_Source__c</fullName>
        <label>Application Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Community</fullName>
                </value>
                <value>
                    <fullName>Webhook</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Federal_Tax_Id__c</fullName>
        <label>Federal Tax Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/LeadsDomain.cls
public inherited sharing class LeadsDomain {

    public static Lead buildFromApplication(ApplicationDTO app) {
        return new Lead(
            FirstName = app.firstName,
            LastName = app.lastName,
            Company = app.companyName,
            Email = app.email,
            Phone = app.phone,
            AnnualRevenue = app.annualRevenue,
            Federal_Tax_Id__c = app.federalTaxId,
            Application_Source__c = app.source
        );
    }
}